live_config_reload = false

[env]
TERM = "xterm-256color"

[window]
dimensions = { columns = 80, lines = 24 }
padding = { x = 10, y = 10 }
decorations = "None"
opacity = 1

[scrolling]
history = 2500

[font]
size = 16
normal = { family = "MesloLGS Nerd Font", style = "Regular" }
bold = { family = "MesloLGS Nerd Font", style = "Bold" }
italic = { family = "MesloLGS Nerd Font", style = "Italic" }
bold_italic = { family = "MesloLGS Nerd Font", style = "Bold Italic" }
glyph_offset = { x = 0, y = 0 }

[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "#282828"
foreground = "#ebdbb2"

[colors.normal]
black = "#282828"
blue = "#458588"
cyan = "#689d6a"
green = "#98971a"
magenta = "#b16286"
red = "#cc241d"
white = "#a89984"
yellow = "#d79921"

[colors.bright]
black = "#928374"
blue = "#83a598"
cyan = "#8ec07c"
green = "#b8bb26"
magenta = "#d3869b"
red = "#fb4934"
white = "#ebdbb2"
yellow = "#fabd2f"

[bell]
animation = "EaseOutExpo"

[selection]
save_to_clipboard = true

[mouse]
bindings = [
    { mouse = "Middle", action = "PasteSelection" },
]

[keyboard]
bindings = [
	# tested
	{ key = "Delete",        mods = "Alt",             chars  = "\u001bD"           },  
	{ key = "Back",          mods = "Super",           chars  = "\u0015"            }, 
	{ key = "Left",          mods = "Alt",             chars  = "\u001Bb"           }, # move the cursor to a word left
	{ key = "Right",         mods = "Alt",             chars = "\u001Bf"            }, # move the cursor to a word right

	# (macOS only)
	{ key = "Left",          mods = "Command",         chars = "\u001bOH",    mode = "AppCursor"   },
	{ key = "Right",         mods = "Command",         chars = "\u001bOF",    mode = "AppCursor"   },
	# { key = "Left",        mods = "Command",         chars = "\u001bOH",    mode = "~AppCursor"  },
	# { key = "Right",       mods = "Command",         chars = "\u001bOF",    mode = "~AppCursor"  },
	# # see example alacritty.yml. keys are from https://docs.rs/glutin/*/glutin/event/enum.VirtualKeyCode.html#variants
	# { key = "S",           mods = "Command",         mode = "Vi",           chars = "\u0013"     },
	# { key = "A",           mods = "Command",         mode = "Vi",           chars = "\u0001"     },

	# Vi Mode
	{ key = "Slash",         mods = "Control",         mode = "~Vi",          chars = "++"         },
	# { key = "L",           mods = "Control",         mode = "~Vi",          chars = "\u000c"     },

	# deprecated/invalid key bindings in latest alacritty
	# { key = "Q",           mods = "Control",         chars  = "\u0011"           } # deprecated
	# { key = "Apostrophe",  mods = "Alt",             chars = "\u001B'"           },
	# { key = "Apostrophe",  mods = "Alt|Shift",       chars = "\u001B\""          },
	# { key = "Grave",       mods = "Alt",             chars = "\u001B`"           },
	# { key = "Grave",       mods = "Alt|Shift",       chars = "\u001B~"           },

	# needs to be tested
	# { key = "Left",        mods = "Alt|Shift",       chars  = "\u001B\u001B[D"   },
	# { key = "Right",       mods = "Alt|Shift",       chars  = "\u001B\u001B[C"   },
	# { key = "PageUp",                                action = "ScrollPageUp"     },
	# { key = "PageUp",      mode = "Alt",             chars = "\u001B[5~"         },
	# { key = "PageUp",      mods = "Shift",           chars = "\u001B[5~"         },
	# { key = "PageDown",                              action = "ScrollPageDown"   },
	# { key = "PageDown",    mode = "Alt",             chars = "\u001B[6~"         },
	# { key = "PageDown",    mods = "Shift",           chars = "\u001B[6~"         },
	# { key = "Home",                                  action = "ScrollToTop"      },
	# { key = "Home",        mode = "Alt",             chars = "\u001BOH"          },
	# { key = "Home",        mods = "Shift",           chars = "\u001B[H"          },
	# { key = "End",                                   action = "ScrollToBottom"   },
	# { key = "End",         mode = "Alt",             chars = "\u001BOF"          },
	# { key = "End",         mods = "Shift",           chars = "\u001B[F"          },
	# { key = "Tab",         mods = "Alt",             chars = "\u001B\t"          },
	# { key = "Tab",         mods = "Alt|Shift",       chars = "\u001B\u001B[Z"    },
	# { key = "Back",                                  chars = "\u007F"            },
	# { key = "Back",        mods = "Alt",             chars = "\u001B\u007F"      },
	# { key = "Back",        mods = "Alt|Shift",       chars = "\u001B\u0008"      },
	# { key = "Space",       mods = "Control",         chars = "\u0000"            },
	# { key = "Space",       mods = "Alt",             chars = "\u0020"            },
	# { key = "Down",        mods = "Alt",             chars = "\u001B\u001B[B"    },
	# { key = "Down",        mods = "Alt|Shift",       chars = "\u001B\u001B[B"    },
	# { key = "Up",          mods = "Alt",             chars = "\u001B\u001B[A"    },
	# { key = "Up",          mods = "Alt|Shift",       chars = "\u001B\u001B[A"    },
	# { key = "A",           mods = "Alt",             chars = "\u001Ba"           },
	# { key = "A",           mods = "Alt|Shift",       chars = "\u001BA"           },
	# { key = "B",           mods = "Alt",             chars = "\u001Bb"           },
	# { key = "B",           mods = "Alt|Shift",       chars = "\u001BB"           },
	# { key = "C",           mods = "Alt",             chars = "\u001Bc"           },
	# { key = "C",           mods = "Alt|Shift",       chars = "\u001BC"           },
	# { key = "D",           mods = "Alt",             chars = "\u001Bd"           },
	# { key = "D",           mods = "Alt|Shift",       chars = "\u001BD"           },
	# { key = "E",           mods = "Alt",             chars = "\u001Be"           },
	# { key = "E",           mods = "Alt|Shift",       chars = "\u001BE"           },
	# { key = "F",           mods = "Alt",             chars = "\u001Bf"           },
	# { key = "F",           mods = "Alt|Shift",       chars = "\u001BF"           },
	# { key = "G",           mods = "Alt",             chars = "\u001Bg"           },
	# { key = "G",           mods = "Alt|Shift",       chars = "\u001BG"           },
	# { key = "H",           mods = "Alt",             chars = "\u001Bh"           },
	# { key = "H",           mods = "Alt|Shift",       chars = "\u001BH"           },
	# { key = "I",           mods = "Alt",             chars = "\u001Bi"           },
	# { key = "I",           mods = "Alt|Shift",       chars = "\u001BI"           },
	# { key = "J",           mods = "Alt",             chars = "\u001Bj"           },
	# { key = "J",           mods = "Alt|Shift",       chars = "\u001BJ"           },
	# { key = "K",           mods = "Alt",             chars = "\u001Bk"           },
	# { key = "K",           mods = "Alt|Shift",       chars = "\u001BK"           },
	# { key = "L",           mods = "Alt",             chars = "\u001Bl"           },
	# { key = "L",           mods = "Alt|Shift",       chars = "\u001BL"           },
	# { key = "M",           mods = "Alt",             chars = "\u001Bm"           },
	# { key = "M",           mods = "Alt|Shift",       chars = "\u001BM"           },
	# { key = "N",           mods = "Alt",             chars = "\u001Bn"           },
	# { key = "N",           mods = "Alt|Shift",       chars = "\u001BN"           },
	# { key = "O",           mods = "Alt",             chars = "\u001Bo"           },
	# { key = "O",           mods = "Alt|Shift",       chars = "\u001BO"           },
	# { key = "P",           mods = "Alt",             chars = "\u001Bp"           },
	# { key = "P",           mods = "Alt|Shift",       chars = "\u001BP"           },
	# { key = "Q",           mods = "Alt",             chars = "\u001Bq"           },
	# { key = "Q",           mods = "Alt|Shift",       chars = "\u001BQ"           },
	# { key = "R",           mods = "Alt",             chars = "\u001Br"           },
	# { key = "R",           mods = "Alt|Shift",       chars = "\u001BR"           },
	# { key = "S",           mods = "Alt",             chars = "\u001Bs"           },
	# { key = "S",           mods = "Alt|Shift",       chars = "\u001BS"           },
	# { key = "T",           mods = "Alt",             chars = "\u001Bt"           },
	# { key = "T",           mods = "Alt|Shift",       chars = "\u001BT"           },
	# { key = "U",           mods = "Alt",             chars = "\u001Bu"           },
	# { key = "U",           mods = "Alt|Shift",       chars = "\u001BU"           },
	# { key = "V",           mods = "Alt",             chars = "\u001Bv"           },
	# { key = "V",           mods = "Alt|Shift",       chars = "\u001BV"           },
	# { key = "W",           mods = "Alt",             chars = "\u001Bw"           },
	# { key = "W",           mods = "Alt|Shift",       chars = "\u001BW"           },
	# { key = "X",           mods = "Alt",             chars = "\u001Bx"           },
	# { key = "X",           mods = "Alt|Shift",       chars = "\u001BX"           },
	# { key = "Y",           mods = "Alt",             chars = "\u001By"           },
	# { key = "Y",           mods = "Alt|Shift",       chars = "\u001BY"           },
	# { key = "Z",           mods = "Alt",             chars = "\u001Bz"           },
	# { key = "Z",           mods = "Alt|Shift",       chars = "\u001BZ"           },
	# { key = "Key1",        mods = "Alt",             chars = "\u001B1"           },
	# { key = "Key1",        mods = "Alt|Shift",       chars = "\u001B!"           },
	# { key = "Key2",        mods = "Alt",             chars = "\u001B2"           },
	# { key = "Key2",        mods = "Alt|Shift",       chars = "\u001B#"           },
	# { key = "Key3",        mods = "Alt",             chars = "\u001B3"           },
	# { key = "Key3",        mods = "Alt|Shift",       chars = "\u001B#"           },
	# { key = "Key4",        mods = "Alt",             chars = "\u001B4"           },
	# { key = "Key4",        mods = "Alt|Shift",       chars = "\u001B$"           },
	# { key = "Key5",        mods = "Alt",             chars = "\u001B5"           },
	# { key = "Key5",        mods = "Alt|Shift",       chars = "\u001B%"           },
	# { key = "Key6",        mods = "Alt",             chars = "\u001B6"           },
	# { key = "Key6",        mods = "Alt|Shift",       chars = "\u001B^"           },
	# { key = "Key7",        mods = "Alt",             chars = "\u001B7"           },
	# { key = "Key7",        mods = "Alt|Shift",       chars = "\u001B&"           },
	# { key = "Key8",        mods = "Alt",             chars = "\u001B8"           },
	# { key = "Key8",        mods = "Alt|Shift",       chars = "\u001B*"           },
	# { key = "Key9",        mods = "Alt",             chars = "\u001B9"           },
	# { key = "Key9",        mods = "Alt|Shift",       chars = "\u001B("           },
	# { key = "Key0",        mods = "Alt",             chars = "\u001B0"           },
	# { key = "Key0",        mods = "Alt|Shift",       chars = "\u001B)"           },
	# { key = "Minus",       mods = "Alt",             chars = "\u001B-"           },
	# { key = "Minus",       mods = "Alt|Shift",       chars = "\u001B_"           },
	# { key = "Equals",      mods = "Alt",             chars = "\u001B="           },
	# { key = "Equals",      mods = "Alt|Shift",       chars = "\u001B+"           },
	# { key = "LBracket",    mods = "Alt",             chars = "\u001B["           },
	# { key = "LBracket",    mods = "Alt|Shift",       chars = "\u001B{"           },
	# { key = "RBracket",    mods = "Alt",             chars = "\u001B]"           },
	# { key = "RBracket",    mods = "Alt|Shift",       chars = "\u001B}"           },
	# { key = "Backslash",   mods = "Alt",             chars = "\u001B\\"          },
	# { key = "Backslash",   mods = "Alt|Shift",       chars = "\u001B|"           },
	# { key = "Semicolon",   mods = "Alt",             chars = "\u001B;"           },
	# { key = "Semicolon",   mods = "Alt|Shift",       chars = "\u001B:"           },
	# { key = "Comma",       mods = "Alt",             chars = "\u001B,"           },
	# { key = "Comma",       mods = "Alt|Shift",       chars = "\u001B<"           },
	# { key = "Period",      mods = "Alt",             chars = "\u001B."           },
	# { key = "Period",      mods = "Alt|Shift",       chars = "\u001B>"           },
	# { key = "Slash",       mods = "Alt",             chars = "\u001B/"           },
	# { key = "Slash",       mods = "Alt|Shift",       chars = "\u001B?"           },
]

